# language setting
language: node_js

# version numbers, testing against multiple versions of node
node_js:
  - 0.10.30

before_script:
  - npm link
  - mkdir -p shippable/codecoverage
after_success:
  - npm run coverage
  - mv coverage/cobertura-coverage.xml shippable/codecoverage/coverage.xml
  - ./node_modules/.bin/jscoverage lib lib-cov
  - ./node_modules/.bin/mocha test/**tests.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js