language: node_js
sudo: false
node_js:
  - 0.12

cache:
   directories:
     - node_modules

before_script:
#  - mkdir -p shippable/codecoverage
  - npm install -g gulp
  - npm install -g codeclimate-test-reporter

after_success:
#  - npm run coverage
#  - mv coverage/cobertura-coverage.xml shippable/codecoverage/coverage.xml
#  - mocha test -R mocha-lcov-reporter
#  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose
#  - cat ./coverage/lcov.info | codeclimate
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate < ./coverage/lcov.info

deploy:
  provider: npm
  email: thaiat@ipelia.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    all_branches: true
    repo: thaiat/generator-sublime
